### ISSUE TITLE
Problem testing a React component that uses parse

### ISSUE THREAD

**Issue by tyagow** [remarkablemark/html-react-parser#169]
##  Expected Behavior

I should be able to test React components that use parse

## Actual Behavior

```
     at parseDOM (../home/devusr/node_modules/html-dom-parser/lib/html-to-dom-server.js:24:3)
      at parse (../home/devusr/node_modules/html-react-parser/index.js:26:5)
```

## Steps to Reproduce

Have a React component that users parse

```
import parse from 'html-react-parser';

[...]

        <p>{parse(newMessageText)}</p>
[...]

Run a test that mounts this component

## Reproducible Demo



## Environment

- Version:     "html-react-parser": "0.13.0",
- Platform:  Jest + docker
- Browser: -

**Comment by remarkablemark** [comment]
Thanks for opening this issue @tyagow. Can you provide a reproducible example? Are you running tests in Node.js environment or browser environment?

**Comment by remarkablemark** [comment]
Closing issue due to inactivity. Feel free to reopen if you're still experiencing an issue.
